/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sat Apr 16 00:43:02 2011"
#define BUILD_TIME (1302878582L)

#define VERSION_NUMBER 0x03040300UL
#define VERSION_FEATURES 0x181e0c46UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x221b117dUL
#define VERSION_SANITY2 0xac8195d8UL

#define VERSION_STRING "3.4.3"
#define VERSION_ID \
 "Windows NetHack graphical Version 3.4.3 - last build Sat Apr 16 00:43:02 2011."

