/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Mon May 09 23:11:43 2011"
#define BUILD_TIME (1304946703L)

#define VERSION_NUMBER 0x00070000UL
#define VERSION_FEATURES 0x181e0c46UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x221b217dUL
#define VERSION_SANITY2 0xac8195d8UL

#define VERSION_STRING "0.7.0"
#define VERSION_ID \
 "Windows NetHack graphical Version 0.7.0 - last build Mon May 09 23:11:43 2011."

