// dalder: extracts the boulders, holes, and stairs from sokoban maps to create nethack data.

#include <stdio.h>
#include <stdlib.h>

#define MAX_OBJECTS 30

int main(int argc, char *argv[])
{
	FILE* in = stdin;
	int bx[MAX_OBJECTS], by[MAX_OBJECTS]; // boulders
	int hx[MAX_OBJECTS], hy[MAX_OBJECTS]; // holes
	int dx[MAX_OBJECTS], dy[MAX_OBJECTS]; // doors
	int b_count, h_count, d_count;
	int upx, upy, downx, downy;
	int c, x, y;
	int max_x = 0, max_y = 0;
	
	
	if (argc >= 2)
	{
		in = fopen(argv[1], "r");
		if (!in)
		{
			fprintf(stderr, "failed to open file: %s\nsorry.\n", argv[1]);
			return 1;
		}
	}
	
	// initialize
	b_count = h_count = d_count = 0;
	upx = upy = downx = downy = -1;
	x = y = 0;
	
	// header info
	printf("## Level description generated by Balder.exe\n");
	printf("LEVEL:\"soko#-#\"\n");
	printf("FLAGS:noteleport,mazelevel,premapped\n");
	printf("INIT_MAP:solidfill,' '\n");
	printf("GEOMETRY:center,center\n");
	printf("\n#12345678901234567890123456789012345678901234567890\n"); // just for ease of use
	printf("MAP\n");
	
	// read the map
	c = fgetc(in);
	while (c != EOF)
	{
		if (c == '#') // comment, ignore the rest of the line
		{
			do
			{
				c = fgetc(in);
			} while (c != EOF && c != '\n');
			if (c == EOF)
				break;
			// Don't count the line break
			c = fgetc(in);
		}
		if (c == 'o' && b_count < MAX_OBJECTS) // boulder
		{
			bx[b_count] = x;
			by[b_count] = y;
			b_count++;
			c = '.';
		}
		if (c == '^' && h_count < MAX_OBJECTS) // hole
		{
			hx[h_count] = x;
			hy[h_count] = y;
			h_count++;
			c = '.';
		}
		if (c == '+' && d_count < MAX_OBJECTS) // door
		{
			dx[d_count] = x;
			dy[d_count] = y;
			d_count++;
			c = '.';
		}
		if (c == '>') // down
		{
			downx = x;
			downy = y;
			c = '.';
		}
		if (c == '<') // up
		{
			upx = x;
			upy = y;
			c = '.';
		}
		if (c == '\n')
		{
			y++;
			max_y = y;
			if (x > max_x)
				max_x = x;
			while (x < max_x)
			{
				fputc(' ', stdout);
				x++;
			}
			x = 0;
		}
		else if (c != '\r')
			x++;
		fputc(c, stdout);
		c = fgetc(in);
	}
	
	// general info
	printf("ENDMAP\n");
	// print the stairs
	if (downx >= 0 && downy >= 0)
		printf("STAIR:(%02d,%02d),down\n", downx, downy);
	if (upx >= 0 && upy >= 0)
		printf("STAIR:(%02d,%02d),up\n", upx, upy);
	// print the doors list
	for (c = 0; c < d_count; c++)
	{
		printf("DOOR:locked,(%02d,%02d)\n",dx[c], dy[c]); // door must be manually set to 'closed' if you don't want it locked
	}
	printf("REGION:(00,00,%02d,%02d),lit,\"ordinary\"\n", max_x, max_y);
	printf("NON_DIGGABLE:(00,00,%02d,%02d)\n", max_x, max_y);
	printf("NON_PASSWALL:(00,00,%02d,%02d)\n", max_x, max_y);
	
	// print the boulder list
	printf("\n");
	for (c = 0; c < b_count; c++)
		printf("OBJECT:('`',\"boulder\"),(%02d,%02d)\n", bx[c], by[c]);
	
	// print the hole list
	printf("\n");	
	for (c = 0; c < h_count; c++)
		printf("TRAP:\"hole\",(%02d,%02d)\n", hx[c], hy[c]);
		
	// loot function
	printf("\n");	
	printf("soko_loot()\n");
	
	// done
	return 0;
}